/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "yqbyngbaigbcxvmtnbtk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxYnluZ2JhaWdiY3h2bXRuYnRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0OTY3ODAsImV4cCI6MjA3MDA3Mjc4MH0.9AxJQ7OXsWhSHL-B8BfsprYGUW_ss1LijVxiJ4AEa54"
